dist: xenial
sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^9
    - php: 7.3
      env: TYPO3_VERSION=^9
    - php: 7.4
      env: TYPO3_VERSION=^9
    - php: 7.2
      env: TYPO3_VERSION=^10
    - php: 7.3
      env: TYPO3_VERSION=^10
    - php: 7.4
      env: TYPO3_VERSION=^10

install:
  - export PROJECT_DIR=$PWD
  - sudo apt-get update -y
  - sudo apt-get -y install build-essential cmake libtool libwebp-dev unzip python-dev autoconf automake m4 nasm pkg-config libpng-dev libmagickcore-dev libmagickwand-dev pngnq
  - pip install setuptools
  # intall mozjpeg
  - cd ~
  - wget https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz
  - tar xf v3.3.1.tar.gz
  - cd mozjpeg-3.3.1
  - autoreconf -fiv
  - mkdir build
  - cd build
  - sh ../configure --disable-shared --enable-static --prefix=/usr/local
  - sudo make install
  - sudo ln -s /usr/local/bin/cjpeg /usr/bin/mozjpeg-cjpeg
  - sudo ln -s /usr/local/bin/jpegtran /usr/bin/mozjpeg-jpegtran
  - cd $PROJECT_DIR

addons:
  apt:
    packages:
      - parallel
      - jpegoptim
      - optipng
      - pngcrush
      - gifsicle
      - pngquant
      # jpgrescan
      - libjpeg-turbo-progs
      - libperl6-slurp-perl
      - libfile-slurp-perl
cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - pwd
  - cd $PROJECT_DIR
  - pwd
  - phpenv config-rm xdebug.ini
  - composer require typo3/minimal=$TYPO3_VERSION
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
