#!/bin/bash

## Description: Install TYPO3 11 with project extension.
## Usage: install-v11
## Example: "ddev install-v11"

VERSION=v11
DATABASE=database_$VERSION
BASE_PATH=/var/www/html/.test/$VERSION

[ -L "/var/www/html/.test/${EXTENSION_KEY}" ] || ln -sr /var/www/html/ "/var/www/html/.test/${EXTENSION_KEY}"
rm -rf $BASE_PATH
mkdir -p $BASE_PATH

mysql -uroot -proot -e "DROP DATABASE IF EXISTS $DATABASE"

composer init --name=inscript/typo3$VERSION --description=TYPO3$VERSION --no-interaction --working-dir $BASE_PATH
composer config --no-plugins allow-plugins.typo3/cms-composer-installers true -d $BASE_PATH
composer config --no-plugins allow-plugins.typo3/class-alias-loader true -d $BASE_PATH
composer config --no-plugins allow-plugins.cweagans/composer-patches true -d $BASE_PATH
composer config --json extra.patches '{"typo3/cms-core": {"Modifies CropVariantCollection and CropVariant classes":"public/typo3conf/ext/imagemod/Resources/Private/Patches/Crop.patch", "Adds rotate command":"public/typo3conf/ext/imagemod/Resources/Private/Patches/11/Core.patch"}, "typo3/cms-backend": {"Sets rotate in image processing configuration":"public/typo3conf/ext/imagemod/Resources/Private/Patches/11/Backend.patch"}, "typo3/cms-fluid": {"Sets rotate in image processing configuration":"public/typo3conf/ext/imagemod/Resources/Private/Patches/11/Fluid.patch"}}' -d $BASE_PATH

composer config repositories.$EXTENSION_KEY path ../$EXTENSION_KEY --working-dir $BASE_PATH
composer req typo3/minimal:'^11.5' typo3/cms-fluid-styled-content:'^11.5' cweagans/composer-patches:'^1.7' typo3/cms-recycler:'^11.5' helhum/typo3-console:'^7.1.2' \ inscript/$EXTENSION_KEY:'@dev' \
         --no-progress --no-interaction --working-dir $BASE_PATH

$BASE_PATH/vendor/bin/typo3cms install:setup -n --database-name $DATABASE
$BASE_PATH/vendor/bin/typo3cms configuration:set 'BE/debug' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'BE/lockSSL' true
$BASE_PATH/vendor/bin/typo3cms configuration:set 'FE/debug' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
$BASE_PATH/vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
$BASE_PATH/vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'

sed -i -e "s/base: ht\//base: \//g" $BASE_PATH/config/sites/main/config.yaml
sed -i -e 's/base: \/en\//base: \//g' $BASE_PATH/config/sites/main/config.yaml
printf "imports:\n  -\n    resource: 'EXT:$EXTENSION_KEY/Configuration/Routing/config.yaml'" >> $BASE_PATH/config/sites/main/config.yaml

cp -r "$BASE_PATH/../$EXTENSION_KEY/.ddev/data-init/fileadmin/" "$BASE_PATH/public/"
mysql -uroot -proot  $DATABASE < "$BASE_PATH/../$EXTENSION_KEY/.ddev/data-init/$DATABASE.sql"

$BASE_PATH/vendor/bin/typo3cms database:updateschema
$BASE_PATH/vendor/bin/typo3cms cache:flush
